
app: /rebuild/app.js
app: /app.js
include: [_media, _images]

title: Kavakings
e-mail: Jim@kavakings.com

logo: _images/waveLogo_transparent_white.png
single-bag-img: http://kavakings.com/image_main/kavaBag_1.jpg
double-bag-img: http://kavakings.com/image_main/kavaBags_2.jpg

carousel: _media
images: _images