
app: /rebuild/app.js
app: /app.js
include: [_media, _images]

title: Kavakings
e-mail: Jim@kavakings.com

logo: https://_images/waveLogo_transparent_white.png
single-bag-img: //_images/kavaBag_1.jpg
double-bag-img: //_images/kavaBags_2.jpg

carousel: _media
images: _images