
app: /app.js
include: [_media, _images]

title: Kavakings
e-mail: Jim@kavakings.com

logo: //kavakings.com/image_main/waveLogo_transparent_white.png
single-bag-img: _images/kavaBag_1.jpg
double-bag-img: _images/kavaBags_2.jpg

carousel: _media
images: _images